apiVersion: v1
kind: Namespace
metadata:
  name: momo-payment
  labels:
    name: momo-payment
    environment: production
    part-of: payment-system
    managed-by: kubernetes
    created-by: ngomse-hub
  annotations:
    description: "Namespace for MoMo Payment Gateway"
    owner: "devops@company.com"
